from turtle import*
while True:
    circle(150)
    up()
    goto(-70,170)
    down()
    color("red")
    begin_fill()
    circle(20)
    end_fill()
    up()
    goto(70,170)
    down()
    begin_fill()
    circle(20)
    end_fill()
    up()
    goto(-95,150)
    down()
    right(90)
    color("black")
    circle(100, 180)
